POST http://localhost:8081/airport/batch
Content-Type: application/json

[
  {
    "ALTITUDE": 13,
    "CITY": "New York",
    "CONTACT_EMAIL": "info@jfkairport.com",
    "CONTACT_PHONE": "+1 718-244-4444",
    "COUNTRY": "United States",
    "DST": "A",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "JFK",
    "ICAO_CODE": "KJFK",
    "LATITUDE": 40.6413,
    "LONGITUDE": -73.7781,
    "NAME": "John F. Kennedy International Airport",
    "NUMBER_OF_GATES": 128,
    "NUMBER_OF_TERMINALS": 6,
    "REGION": "North America",
    "TIMEZONE": "America/New_York",
    "TZ_DATABASE_TIME_ZONE": "America/New_York",
    "WEBSITE": "https://www.jfkairport.com"
  },
  {
    "ALTITUDE": 116,
    "CITY": "London",
    "CONTACT_EMAIL": "contact@heathrow.com",
    "CONTACT_PHONE": "+44 20 8759 4321",
    "COUNTRY": "United Kingdom",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "LHR",
    "ICAO_CODE": "EGLL",
    "LATITUDE": 51.47,
    "LONGITUDE": -0.4543,
    "NAME": "Heathrow Airport",
    "NUMBER_OF_GATES": 185,
    "NUMBER_OF_TERMINALS": 5,
    "REGION": "Europe",
    "TIMEZONE": "Europe/London",
    "TZ_DATABASE_TIME_ZONE": "Europe/London",
    "WEBSITE": "https://www.heathrow.com"
  },
  {
    "ALTITUDE": 35,
    "CITY": "Tokyo",
    "CONTACT_EMAIL": "customer-support@haneda-airport.jp",
    "CONTACT_PHONE": "+81 3-5757-8111",
    "COUNTRY": "Japan",
    "DST": "J",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "HND",
    "ICAO_CODE": "RJTT",
    "LATITUDE": 35.5494,
    "LONGITUDE": 139.7798,
    "NAME": "Haneda Airport",
    "NUMBER_OF_GATES": 85,
    "NUMBER_OF_TERMINALS": 3,
    "REGION": "Asia",
    "TIMEZONE": "Asia/Tokyo",
    "TZ_DATABASE_TIME_ZONE": "Asia/Tokyo",
    "WEBSITE": "https://www.haneda-airport.jp"
  },
  {
    "ALTITUDE": 234,
    "CITY": "Dubai",
    "CONTACT_EMAIL": "feedback@dubaiairports.ae",
    "CONTACT_PHONE": "+971 4 224 5555",
    "COUNTRY": "United Arab Emirates",
    "DST": "U",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "DXB",
    "ICAO_CODE": "OMDB",
    "LATITUDE": 25.2532,
    "LONGITUDE": 55.3657,
    "NAME": "Dubai International Airport",
    "NUMBER_OF_GATES": 200,
    "NUMBER_OF_TERMINALS": 3,
    "REGION": "Middle East",
    "TIMEZONE": "Asia/Dubai",
    "TZ_DATABASE_TIME_ZONE": "Asia/Dubai",
    "WEBSITE": "https://www.dubaiairports.ae"
  },
  {
    "ALTITUDE": 308,
    "CITY": "Denver",
    "CONTACT_EMAIL": "customerservice@flydenver.com",
    "CONTACT_PHONE": "+1 303-342-2000",
    "COUNTRY": "United States",
    "DST": "A",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "DEN",
    "ICAO_CODE": "KDEN",
    "LATITUDE": 39.8561,
    "LONGITUDE": -104.6737,
    "NAME": "Denver International Airport",
    "NUMBER_OF_GATES": 146,
    "NUMBER_OF_TERMINALS": 1,
    "REGION": "North America",
    "TIMEZONE": "America/Denver",
    "TZ_DATABASE_TIME_ZONE": "America/Denver",
    "WEBSITE": "https://www.flydenver.com"
  },
  {
    "ALTITUDE": 8,
    "CITY": "Sydney",
    "CONTACT_EMAIL": "feedback@sydneyairport.com.au",
    "CONTACT_PHONE": "+61 2 9667 9111",
    "COUNTRY": "Australia",
    "DST": "O",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "SYD",
    "ICAO_CODE": "YSSY",
    "LATITUDE": -33.9461,
    "LONGITUDE": 151.1772,
    "NAME": "Sydney Kingsford Smith Airport",
    "NUMBER_OF_GATES": 45,
    "NUMBER_OF_TERMINALS": 3,
    "REGION": "Oceania",
    "TIMEZONE": "Australia/Sydney",
    "TZ_DATABASE_TIME_ZONE": "Australia/Sydney",
    "WEBSITE": "https://www.sydneyairport.com.au"
  },
  {
    "ALTITUDE": 791,
    "CITY": "Mexico City",
    "CONTACT_EMAIL": "contacto@aicm.com.mx",
    "CONTACT_PHONE": "+52 55 2482 2400",
    "COUNTRY": "Mexico",
    "DST": "M",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "MEX",
    "ICAO_CODE": "MMMX",
    "LATITUDE": 19.4363,
    "LONGITUDE": -99.0721,
    "NAME": "Benito Juárez International Airport",
    "NUMBER_OF_GATES": 72,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "North America",
    "TIMEZONE": "America/Mexico_City",
    "TZ_DATABASE_TIME_ZONE": "America/Mexico_City",
    "WEBSITE": "https://www.aicm.com.mx"
  },
  {
    "ALTITUDE": 102,
    "CITY": "Paris",
    "CONTACT_EMAIL": "contact@parisaeroport.fr",
    "CONTACT_PHONE": "+33 1 70 36 39 50",
    "COUNTRY": "France",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "CDG",
    "ICAO_CODE": "LFPG",
    "LATITUDE": 49.0097,
    "LONGITUDE": 2.5479,
    "NAME": "Charles de Gaulle Airport",
    "NUMBER_OF_GATES": 210,
    "NUMBER_OF_TERMINALS": 3,
    "REGION": "Europe",
    "TIMEZONE": "Europe/Paris",
    "TZ_DATABASE_TIME_ZONE": "Europe/Paris",
    "WEBSITE": "https://www.parisaeroport.fr"
  },
  {
    "ALTITUDE": 4,
    "CITY": "Singapore",
    "CONTACT_EMAIL": "feedback@changiairport.com",
    "CONTACT_PHONE": "+65 6595 6868",
    "COUNTRY": "Singapore",
    "DST": "S",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "SIN",
    "ICAO_CODE": "WSSS",
    "LATITUDE": 1.3644,
    "LONGITUDE": 103.9915,
    "NAME": "Changi Airport",
    "NUMBER_OF_GATES": 100,
    "NUMBER_OF_TERMINALS": 4,
    "REGION": "Asia",
    "TIMEZONE": "Asia/Singapore",
    "TZ_DATABASE_TIME_ZONE": "Asia/Singapore",
    "WEBSITE": "https://www.changiairport.com"
  },
  {
    "ALTITUDE": 128,
    "CITY": "Toronto",
    "CONTACT_EMAIL": "customer.service@torontopearson.com",
    "CONTACT_PHONE": "+1 416-776-3000",
    "COUNTRY": "Canada",
    "DST": "A",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "YYZ",
    "ICAO_CODE": "CYYZ",
    "LATITUDE": 43.6777,
    "LONGITUDE": -79.6248,
    "NAME": "Toronto Pearson International Airport",
    "NUMBER_OF_GATES": 98,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "North America",
    "TIMEZONE": "America/Toronto",
    "TZ_DATABASE_TIME_ZONE": "America/Toronto",
    "WEBSITE": "https://www.torontopearson.com"
  },
  {
    "ALTITUDE": 42,
    "CITY": "Frankfurt",
    "CONTACT_EMAIL": "info@fraport.de",
    "CONTACT_PHONE": "+49 69 6900",
    "COUNTRY": "Germany",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "FRA",
    "ICAO_CODE": "EDDF",
    "LATITUDE": 50.0333,
    "LONGITUDE": 8.5706,
    "NAME": "Frankfurt Airport",
    "NUMBER_OF_GATES": 140,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Europe",
    "TIMEZONE": "Europe/Berlin",
    "TZ_DATABASE_TIME_ZONE": "Europe/Berlin",
    "WEBSITE": "https://www.frankfurt-airport.com"
  },
  {
    "ALTITUDE": 2,
    "CITY": "Hong Kong",
    "CONTACT_EMAIL": "customer@hkairport.com",
    "CONTACT_PHONE": "+852 2181 8888",
    "COUNTRY": "Hong Kong",
    "DST": "H",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "HKG",
    "ICAO_CODE": "VHHH",
    "LATITUDE": 22.308,
    "LONGITUDE": 113.9185,
    "NAME": "Hong Kong International Airport",
    "NUMBER_OF_GATES": 80,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Asia",
    "TIMEZONE": "Asia/Hong_Kong",
    "TZ_DATABASE_TIME_ZONE": "Asia/Hong_Kong",
    "WEBSITE": "https://www.hongkongairport.com"
  },
  {
    "ALTITUDE": 808,
    "CITY": "Johannesburg",
    "CONTACT_EMAIL": "customercare@airports.co.za",
    "CONTACT_PHONE": "+27 11 921 6262",
    "COUNTRY": "South Africa",
    "DST": "S",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "JNB",
    "ICAO_CODE": "FAOR",
    "LATITUDE": -26.1392,
    "LONGITUDE": 28.246,
    "NAME": "O.R. Tambo International Airport",
    "NUMBER_OF_GATES": 60,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Africa",
    "TIMEZONE": "Africa/Johannesburg",
    "TZ_DATABASE_TIME_ZONE": "Africa/Johannesburg",
    "WEBSITE": "https://www.airports.co.za"
  },
  {
    "ALTITUDE": 12,
    "CITY": "Amsterdam",
    "CONTACT_EMAIL": "info@schiphol.nl",
    "CONTACT_PHONE": "+31 20 794 0800",
    "COUNTRY": "Netherlands",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "AMS",
    "ICAO_CODE": "EHAM",
    "LATITUDE": 52.3081,
    "LONGITUDE": 4.7642,
    "NAME": "Amsterdam Airport Schiphol",
    "NUMBER_OF_GATES": 110,
    "NUMBER_OF_TERMINALS": 1,
    "REGION": "Europe",
    "TIMEZONE": "Europe/Amsterdam",
    "TZ_DATABASE_TIME_ZONE": "Europe/Amsterdam",
    "WEBSITE": "https://www.schiphol.nl"
  },
  {
    "ALTITUDE": 5,
    "CITY": "Seoul",
    "CONTACT_EMAIL": "callcenter@airport.kr",
    "CONTACT_PHONE": "+82 2 2660 2114",
    "COUNTRY": "South Korea",
    "DST": "K",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "ICN",
    "ICAO_CODE": "RKSI",
    "LATITUDE": 37.4692,
    "LONGITUDE": 126.4505,
    "NAME": "Incheon International Airport",
    "NUMBER_OF_GATES": 120,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Asia",
    "TIMEZONE": "Asia/Seoul",
    "TZ_DATABASE_TIME_ZONE": "Asia/Seoul",
    "WEBSITE": "https://www.airport.kr"
  },
  {
    "ALTITUDE": 156,
    "CITY": "Madrid",
    "CONTACT_EMAIL": "atencion.cliente@aena.es",
    "CONTACT_PHONE": "+34 913 21 10 00",
    "COUNTRY": "Spain",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "MAD",
    "ICAO_CODE": "LEMD",
    "LATITUDE": 40.4936,
    "LONGITUDE": -3.5668,
    "NAME": "Adolfo Suárez Madrid-Barajas Airport",
    "NUMBER_OF_GATES": 90,
    "NUMBER_OF_TERMINALS": 4,
    "REGION": "Europe",
    "TIMEZONE": "Europe/Madrid",
    "TZ_DATABASE_TIME_ZONE": "Europe/Madrid",
    "WEBSITE": "https://www.aena.es"
  },
  {
    "ALTITUDE": 4,
    "CITY": "Bangkok",
    "CONTACT_EMAIL": "contact@bangkokairportonline.com",
    "CONTACT_PHONE": "+66 2 132 1888",
    "COUNTRY": "Thailand",
    "DST": "U",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "BKK",
    "ICAO_CODE": "VTBS",
    "LATITUDE": 13.6811,
    "LONGITUDE": 100.7475,
    "NAME": "Suvarnabhumi Airport",
    "NUMBER_OF_GATES": 120,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Asia",
    "TIMEZONE": "Asia/Bangkok",
    "TZ_DATABASE_TIME_ZONE": "Asia/Bangkok",
    "WEBSITE": "https://www.bangkokairportonline.com"
  },
  {
    "ALTITUDE": 21,
    "CITY": "Rome",
    "CONTACT_EMAIL": "customer.relations@adr.it",
    "CONTACT_PHONE": "+39 06 65951",
    "COUNTRY": "Italy",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "FCO",
    "ICAO_CODE": "LIRF",
    "LATITUDE": 41.8045,
    "LONGITUDE": 12.2508,
    "NAME": "Leonardo da Vinci-Fiumicino Airport",
    "NUMBER_OF_GATES": 75,
    "NUMBER_OF_TERMINALS": 3,
    "REGION": "Europe",
    "TIMEZONE": "Europe/Rome",
    "TZ_DATABASE_TIME_ZONE": "Europe/Rome",
    "WEBSITE": "https://www.adr.it"
  },
  {
    "ALTITUDE": 132,
    "CITY": "Chicago",
    "CONTACT_EMAIL": "feedback@flychicago.com",
    "CONTACT_PHONE": "+1 773 686 2200",
    "COUNTRY": "United States",
    "DST": "A",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "ORD",
    "ICAO_CODE": "KORD",
    "LATITUDE": 41.9742,
    "LONGITUDE": -87.9073,
    "NAME": "O'Hare International Airport",
    "NUMBER_OF_GATES": 182,
    "NUMBER_OF_TERMINALS": 4,
    "REGION": "North America",
    "TIMEZONE": "America/Chicago",
    "TZ_DATABASE_TIME_ZONE": "America/Chicago",
    "WEBSITE": "https://www.flychicago.com"
  },
  {
    "ALTITUDE": 5,
    "CITY": "Shanghai",
    "CONTACT_EMAIL": "service@shairport.com",
    "CONTACT_PHONE": "+86 21 96990",
    "COUNTRY": "China",
    "DST": "U",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "PVG",
    "ICAO_CODE": "ZSPD",
    "LATITUDE": 31.1434,
    "LONGITUDE": 121.8052,
    "NAME": "Shanghai Pudong International Airport",
    "NUMBER_OF_GATES": 110,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Asia",
    "TIMEZONE": "Asia/Shanghai",
    "TZ_DATABASE_TIME_ZONE": "Asia/Shanghai",
    "WEBSITE": "https://www.shairport.com"
  },
  {
    "ALTITUDE": 8,
    "CITY": "Los Angeles",
    "CONTACT_EMAIL": "customerservice@lawa.org",
    "CONTACT_PHONE": "+1 424 646 5252",
    "COUNTRY": "United States",
    "DST": "A",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "LAX",
    "ICAO_CODE": "KLAX",
    "LATITUDE": 33.9416,
    "LONGITUDE": -118.4085,
    "NAME": "Los Angeles International Airport",
    "NUMBER_OF_GATES": 146,
    "NUMBER_OF_TERMINALS": 9,
    "REGION": "North America",
    "TIMEZONE": "America/Los_Angeles",
    "TZ_DATABASE_TIME_ZONE": "America/Los_Angeles",
    "WEBSITE": "https://www.flylax.com"
  },
  {
    "ALTITUDE": 46,
    "CITY": "Moscow",
    "CONTACT_EMAIL": "info@svo.aero",
    "CONTACT_PHONE": "+7 495 578 6565",
    "COUNTRY": "Russia",
    "DST": "M",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "SVO",
    "ICAO_CODE": "UUEE",
    "LATITUDE": 55.9726,
    "LONGITUDE": 37.4146,
    "NAME": "Sheremetyevo International Airport",
    "NUMBER_OF_GATES": 70,
    "NUMBER_OF_TERMINALS": 6,
    "REGION": "Europe",
    "TIMEZONE": "Europe/Moscow",
    "TZ_DATABASE_TIME_ZONE": "Europe/Moscow",
    "WEBSITE": "https://www.svo.aero"
  },
  {
    "ALTITUDE": 3,
    "CITY": "Istanbul",
    "CONTACT_EMAIL": "contact@igairport.com",
    "CONTACT_PHONE": "+90 212 463 3000",
    "COUNTRY": "Turkey",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "IST",
    "ICAO_CODE": "LTFM",
    "LATITUDE": 41.2622,
    "LONGITUDE": 28.7278,
    "NAME": "Istanbul Airport",
    "NUMBER_OF_GATES": 143,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Middle East",
    "TIMEZONE": "Europe/Istanbul",
    "TZ_DATABASE_TIME_ZONE": "Europe/Istanbul",
    "WEBSITE": "https://www.igairport.com"
  },
  {
    "ALTITUDE": 15,
    "CITY": "São Paulo",
    "CONTACT_EMAIL": "sac@gru.com.br",
    "CONTACT_PHONE": "+55 11 2445 2945",
    "COUNTRY": "Brazil",
    "DST": "S",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "GRU",
    "ICAO_CODE": "SBGR",
    "LATITUDE": -23.4356,
    "LONGITUDE": -46.4731,
    "NAME": "Guarulhos International Airport",
    "NUMBER_OF_GATES": 55,
    "NUMBER_OF_TERMINALS": 3,
    "REGION": "South America",
    "TIMEZONE": "America/Sao_Paulo",
    "TZ_DATABASE_TIME_ZONE": "America/Sao_Paulo",
    "WEBSITE": "https://www.gru.com.br"
  },
  {
    "ALTITUDE": 92,
    "CITY": "Mumbai",
    "CONTACT_EMAIL": "feedback@csia.in",
    "CONTACT_PHONE": "+91 22 6685 1010",
    "COUNTRY": "India",
    "DST": "N",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "BOM",
    "ICAO_CODE": "VABB",
    "LATITUDE": 19.0887,
    "LONGITUDE": 72.8679,
    "NAME": "Chhatrapati Shivaji Maharaj International Airport",
    "NUMBER_OF_GATES": 60,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Asia",
    "TIMEZONE": "Asia/Kolkata",
    "TZ_DATABASE_TIME_ZONE": "Asia/Kolkata",
    "WEBSITE": "https://www.csia.in"
  },
  {
    "ALTITUDE": 5,
    "CITY": "Kuala Lumpur",
    "CONTACT_EMAIL": "helpdesk@klia.com.my",
    "CONTACT_PHONE": "+60 3 8777 8888",
    "COUNTRY": "Malaysia",
    "DST": "N",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "KUL",
    "ICAO_CODE": "WMKK",
    "LATITUDE": 2.7456,
    "LONGITUDE": 101.7099,
    "NAME": "Kuala Lumpur International Airport",
    "NUMBER_OF_GATES": 78,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Asia",
    "TIMEZONE": "Asia/Kuala_Lumpur",
    "TZ_DATABASE_TIME_ZONE": "Asia/Kuala_Lumpur",
    "WEBSITE": "https://www.klia.com.my"
  },
  {
    "ALTITUDE": 105,
    "CITY": "Vienna",
    "CONTACT_EMAIL": "info@viennaairport.com",
    "CONTACT_PHONE": "+43 1 7007 22233",
    "COUNTRY": "Austria",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "VIE",
    "ICAO_CODE": "LOWW",
    "LATITUDE": 48.1103,
    "LONGITUDE": 16.5697,
    "NAME": "Vienna International Airport",
    "NUMBER_OF_GATES": 45,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Europe",
    "TIMEZONE": "Europe/Vienna",
    "TZ_DATABASE_TIME_ZONE": "Europe/Vienna",
    "WEBSITE": "https://www.viennaairport.com"
  },
  {
    "ALTITUDE": 12,
    "CITY": "Brussels",
    "CONTACT_EMAIL": "contact@brusselsairport.be",
    "CONTACT_PHONE": "+32 900 70 000",
    "COUNTRY": "Belgium",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "BRU",
    "ICAO_CODE": "EBBR",
    "LATITUDE": 50.9014,
    "LONGITUDE": 4.4844,
    "NAME": "Brussels Airport",
    "NUMBER_OF_GATES": 54,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Europe",
    "TIMEZONE": "Europe/Brussels",
    "TZ_DATABASE_TIME_ZONE": "Europe/Brussels",
    "WEBSITE": "https://www.brusselsairport.be"
  },
  {
    "ALTITUDE": 35,
    "CITY": "Doha",
    "CONTACT_EMAIL": "feedback@dohaairport.com.qa",
    "CONTACT_PHONE": "+974 4010 6666",
    "COUNTRY": "Qatar",
    "DST": "U",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "DOH",
    "ICAO_CODE": "OTHH",
    "LATITUDE": 25.2609,
    "LONGITUDE": 51.6138,
    "NAME": "Hamad International Airport",
    "NUMBER_OF_GATES": 65,
    "NUMBER_OF_TERMINALS": 1,
    "REGION": "Middle East",
    "TIMEZONE": "Asia/Qatar",
    "TZ_DATABASE_TIME_ZONE": "Asia/Qatar",
    "WEBSITE": "https://www.dohaairport.com.qa"
  },
  {
    "ALTITUDE": 8,
    "CITY": "San Francisco",
    "CONTACT_EMAIL": "customer_care@flysfo.com",
    "CONTACT_PHONE": "+1 650 821 8211",
    "COUNTRY": "United States",
    "DST": "A",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "SFO",
    "ICAO_CODE": "KSFO",
    "LATITUDE": 37.6213,
    "LONGITUDE": -122.379,
    "NAME": "San Francisco International Airport",
    "NUMBER_OF_GATES": 94,
    "NUMBER_OF_TERMINALS": 4,
    "REGION": "North America",
    "TIMEZONE": "America/Los_Angeles",
    "TZ_DATABASE_TIME_ZONE": "America/Los_Angeles",
    "WEBSITE": "https://www.flysfo.com"
  },
  {
    "ALTITUDE": 53,
    "CITY": "Beijing",
    "CONTACT_EMAIL": "customerservice@bcia.com.cn",
    "CONTACT_PHONE": "+86 10 96158",
    "COUNTRY": "China",
    "DST": "U",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "PEK",
    "ICAO_CODE": "ZBAA",
    "LATITUDE": 40.0799,
    "LONGITUDE": 116.6031,
    "NAME": "Beijing Capital International Airport",
    "NUMBER_OF_GATES": 120,
    "NUMBER_OF_TERMINALS": 3,
    "REGION": "Asia",
    "TIMEZONE": "Asia/Shanghai",
    "TZ_DATABASE_TIME_ZONE": "Asia/Shanghai",
    "WEBSITE": "https://www.bcia.com.cn"
  },
  {
    "ALTITUDE": 6,
    "CITY": "Athens",
    "CONTACT_EMAIL": "info@aia.gr",
    "CONTACT_PHONE": "+30 210 353 0000",
    "COUNTRY": "Greece",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "ATH",
    "ICAO_CODE": "LGAV",
    "LATITUDE": 37.9364,
    "LONGITUDE": 23.9445,
    "NAME": "Athens International Airport",
    "NUMBER_OF_GATES": 48,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Europe",
    "TIMEZONE": "Europe/Athens",
    "TZ_DATABASE_TIME_ZONE": "Europe/Athens",
    "WEBSITE": "https://www.aia.gr"
  },
  {
    "ALTITUDE": 14,
    "CITY": "Copenhagen",
    "CONTACT_EMAIL": "contact@cph.dk",
    "CONTACT_PHONE": "+45 32 31 32 31",
    "COUNTRY": "Denmark",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "CPH",
    "ICAO_CODE": "EKCH",
    "LATITUDE": 55.618,
    "LONGITUDE": 12.6508,
    "NAME": "Copenhagen Airport",
    "NUMBER_OF_GATES": 60,
    "NUMBER_OF_TERMINALS": 3,
    "REGION": "Europe",
    "TIMEZONE": "Europe/Copenhagen",
    "TZ_DATABASE_TIME_ZONE": "Europe/Copenhagen",
    "WEBSITE": "https://www.cph.dk"
  },
  {
    "ALTITUDE": 88,
    "CITY": "Warsaw",
    "CONTACT_EMAIL": "customer.service@lotnisko-chopina.pl",
    "CONTACT_PHONE": "+48 22 650 42 20",
    "COUNTRY": "Poland",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "WAW",
    "ICAO_CODE": "EPWA",
    "LATITUDE": 52.1657,
    "LONGITUDE": 20.9671,
    "NAME": "Warsaw Chopin Airport",
    "NUMBER_OF_GATES": 40,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Europe",
    "TIMEZONE": "Europe/Warsaw",
    "TZ_DATABASE_TIME_ZONE": "Europe/Warsaw",
    "WEBSITE": "https://www.lotnisko-chopina.pl"
  },
  {
    "ALTITUDE": 2,
    "CITY": "Lisbon",
    "CONTACT_EMAIL": "info@ana.pt",
    "CONTACT_PHONE": "+351 218 413 500",
    "COUNTRY": "Portugal",
    "DST": "E",
    "HAS_INTERNATIONAL_FLIGHTS": true,
    "IATA_CODE": "LIS",
    "ICAO_CODE": "LPPT",
    "LATITUDE": 38.7742,
    "LONGITUDE": -9.1342,
    "NAME": "Humberto Delgado Airport",
    "NUMBER_OF_GATES": 35,
    "NUMBER_OF_TERMINALS": 2,
    "REGION": "Europe",
    "TIMEZONE": "Europe/Lisbon",
    "TZ_DATABASE_TIME_ZONE": "Europe/Lisbon",
    "WEBSITE": "https://www.ana.pt"
  }
]